import Footer from '@/components/Footer/Footer'
import Header from '@/components/Header'
import type { Metadata } from 'next'
import { Bai_Jamjuree } from 'next/font/google'
import '../../assets/styles/globals.scss'
import { useMediaQuery } from '@/hooks/useMediaQuery'

const bai = Bai_Jamjuree({
	subsets: ['latin'],
	weight: ['300', '400', '500', '600', '700'],
	display: 'swap',
	variable: '--bai',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children, }: Readonly<{
	children: React.ReactNode
}>) {

	return (
		<html lang='en'>
			<body className={bai.className}>
				<div className="auth-page">
					<div className="auth-page__header">
						<Header />

					</div>
					{children}
				</div>
			</body>
		</html>
	)
}
