import Image from 'next/image'
import Modal from '../Modal'
import styles from './FaModal.module.scss'
import qrImg from '../../../images/qr.png'
import ButtonBorderGradient from '@/components/ui/buttons/ButtonBorderGradient'
type Props = {
	isOpen?: any
	onClose?: any
	onClick?: () => void
}
const FaModal = ({ isOpen, onClose, onClick }: Props) => {
	return <Modal isOpen={isOpen} onClose={onClose} className={styles.modal} >
		<div className={styles.modal__block}>
			<div className={styles.modal__title}>2FA Setup</div>
			<div className={styles.modal__text}>
				<p><b>1. Scan QR Code:</b> Use your authenticator app to scan the QR code provided on the screen. Alternatively, manually enter the provided key if needed.</p>
			</div>
			<div className={styles.modal__qr}>
				<Image src={qrImg} alt={'img'} />
			</div>
			<div className={styles.modal__code}>Q592FK32</div>
			<div className={styles.modal__text}>
				<p>
					<b>2. Verify Setup:</b> Enter the code generated by the authenticator app to verify that it&apos;s set up correctly.
				</p>
			</div>
			<div className={styles.modal__input}>
				<input type="text" placeholder='Enter 6 digit code' />
			</div>
			<div className={styles.modal__text}>
				<p>
					<b>3. Save Backup Codes:</b> Save backup key in a secure place in case you lose access to your authenticator app.
				</p>
			</div>
			<ButtonBorderGradient onClick={onClick} name={'activate'} formBtn={true} />
		</div>

	</Modal>
}

export default FaModal